x-todo_app: &todo_app
  build:
    context: .
    dockerfile: ./docker/Dockerfile
  # image: python-todo-app:1.0
  tmpfs:
    - /tmp
  tty: true
  stdin_open: true
  volumes:
    - ./todo_app:/app:cached
  #   - solids_bundle:/usr/local/bundle
  environment:
    - DB_URL=postgres://postgres:password@db:5432
    - EDITOR=vim
  working_dir: /app

services:
  todo_app: 
    <<: *todo_app
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 3929:8000
    depends_on:
      - pgdb
      - mysqldb
    networks:
      - local-network
    develop:
      watch:
        - action: sync
          path: .
          target: /app
    #     - action: rebuild
    #       path: ./Gemfile
  pgdb:
    image: postgres:17
    ports:
      - 3931:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - local-network
  mysqldb:
    image: mysql:8
    ports:
      - 3932:3306
    restart: always
    environment:
      MY_SQL_USER: root
      MY_SQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
networks:
  local-network:
    driver: bridge
